### PR TITLE
define global variables in global.c

### PR DESCRIPTION
**Pull request by yatli**

### CODE REVIEW

**Comment by jay7x** [comment]
Hi @yatli! I'm ok to merge this but just curious what is the reason for the change? Better style I guess, right?

**Comment by yatli** [comment]
Hi @jay7x !

I have problems building it with gcc because the header is included from multiple sources, and these are regarded as multiple definitions of the same symbol. This PR makes sure the variables in the header are pulled into the sources as external declarations, while a single definition is done in global.c

**Comment by jay7x** [comment]
> I have problems building it with gcc because the header is included from multiple sources, and these are regarded as multiple definitions of the same symbol. This PR makes sure the variables in the header are pulled into the sources as external declarations, while a single definition is done in global.c

Ah, I see.. ok, going to merge it then! Thank you for your contribution!

> Also curious: what's the toolchain of your choice? kexecboot built with my gcc toolchain is like 3x bigger in size, which makes it challenging to pack into Zaurus initramfs.

I'm not really active in this part for last years tbh.. but I was using OpenEmbedded to cross-compile while ago. I guess this layer is the right one: http://cgit.openembedded.org/meta-handheld/

Andrea @andrea-adami was touching it recently enough as I see (11 month ago). Maybe he can suggest something..

Wrt the image size main trick is `klibc` I believe.. we're linking with `klibc` which is bare-minimal (or maybe even partial) libc implementation.

Some links to have a look on:
- http://cgit.openembedded.org/meta-handheld/tree/recipes-kernel/linux/linux-kexecboot_4.4.bb#n27
- http://cgit.openembedded.org/meta-openembedded/tree/meta-initramfs/recipes-core/images/initramfs-kexecboot-klibc-image.bb
- http://cgit.openembedded.org/meta-openembedded/tree/meta-initramfs/recipes-devtools/klibc

**Comment by yatli** [comment]
@greguu also mentioned klibc but my brain autoskipped the part I don't understand :O
Thanks for the links, I think that's spot on!

**Comment by andrea-adami** [comment]
Hello,
hope allis well.
Sorry but life took me away...I plan to test kexecboot build with recent OE toolchains.
We must implement some fixes Khem put in OE for other compilers.
Klibc build needs also to be tested.

Hope to do that soon.
Cheers
Andrea

**Comment by andrea-adami** [comment]
Ah, if it is for zaurus, pls check the sizes of these pre-compiled initramfs and kernels to get an idea:

https://github.com/LinuxPDA/linux-kexecboot/tree/master/zaurus

As Jay7 says the trick is to link kexecboot against klibc, statically.

Cheers
Andrea

**Pull request merged**
